mysql:
    # TODO create mysql db and models
    url: sqlite:////tmp/test.db
    host: localhost
    user: root
    passwd: my secret password
    db: write-math

authentication:
    digest_db:
        name: MyAuthRealm
    admin:
        name: admin
        password: test
    secret_key: super secret string

other:
    preprocessing_queue:
        - preprocessing.scale_and_center
        - preprocessing.dot_reduction
        - preprocessing.connect_lines
    use_anonymous: yes